# Generated by Django 5.2.1 on 2025-06-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Reserved'), ('O', 'Occupied')], default='A', max_length=1)),
                ('block', models.IntegerField()),
                ('lot', models.IntegerField()),
                ('plot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_birth', models.CharField(blank=True, max_length=25, null=True)),
                ('dete_of_death', models.CharField(blank=True, max_length=25, null=True)),
                ('grave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spcem.grave')),
            ],
        ),
        migrations.AddField(
            model_name='grave',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spcem.owner'),
        ),
    ]
